### PR TITLE
Added permissions to run on all cragslist domains

### PR DESCRIPTION
**Pull request by darsain**
Wasn't running on a lot of TLDs used by graigslist, so I did a regex match on http://www.craigslist.org/about/sites to get all the TLDs, and added them to manifest.

Also I've replaced `http` with `*` so it would also run on `https`.

### CODE REVIEW

**Comment by darsain** [comment]
If there will be new TLDs added in future, this is the script used:

``` js
(function () {
    var domains = [];
    jQuery('a[href*="craigslist"]').each(function (i, link) {
        var domain = jQuery(link).attr('href').match(/craigslist\.[a-z.]+/i);
        if (domain && domains.indexOf(domain[0]) === -1) {
            domains.push(domain[0]);
        }
    });

    var manifested = '';
    domains.forEach(function (domain, i) { console.log(i);
        manifested += '"*://*.' + domain + '/*"' + (i < domains.length-1 ? ',\n' : '');
    });

    console.log(manifested);
}());
```

Just copy & paste the output into manifest.

**Comment by fooblahblah** [comment]
Thanks for your submissions. I'll get them in this weekend.

**Comment by darsain** [comment]
Shit, just noticed the regex left out all domains like `.co.uk`. **So don't merge this PR!** :shit: But replace the current permissions with the proper list below. I''ve already deleted my fork, and am too lazy to redo it :)

```
"*://*.craigslist.org/*",
"*://*.craigslist.ca/*",
"*://*.craigslist.at/*",
"*://*.craigslist.cz/*",
"*://*.craigslist.fi/*",
"*://*.craigslist.de/*",
"*://*.craigslist.gr/*",
"*://*.craigslist.it/*",
"*://*.craigslist.pl/*",
"*://*.craigslist.pt/*",
"*://*.craigslist.es/*",
"*://*.craigslist.se/*",
"*://*.craigslist.ch/*",
"*://*.craigslist.com.tr/*",
"*://*.craigslist.co.uk/*",
"*://*.craigslist.com.cn/*",
"*://*.craigslist.hk/*",
"*://*.craigslist.co.in/*",
"*://*.craigslist.jp/*",
"*://*.craigslist.co.kr/*",
"*://*.craigslist.com.ph/*",
"*://*.craigslist.com.sg/*",
"*://*.craigslist.com.tw/*",
"*://*.craigslist.co.th/*",
"*://*.craigslist.com.au/*",
"*://*.craigslist.co.nz/*",
"*://*.craigslist.com.mx/*",
"*://*.craigslist.co.za/*",
"*://*.craigslist.com/*"
```

I'm also updating the script above with a proper regex.

**Comment by fooblahblah** [comment]
I published a new version of the extension with the new matches. Thanks.

**Pull request closed without merging**
